apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
  template:
    metadata:
      labels:
        app: reddit
    spec:
      containers:
      - name: reddit
        image: gcr.io/reddit-fastapi-deploy/reddit-app:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"



